### ISSUE TITLE
issuses

### ISSUE THREAD

**Issue by leonxs** [forza-panino/Sniper-Bot#3]
F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_web3-core-requestmanager@1.6.0@web3-core-requestmanager\lib\index.js:296
            return callback(new Error(`Wrong response id ${result.id} (expected: ${payload.id}) in ${JSON.stringify(payload)}`));
                            ^

Error: Wrong response id 4118629551787325 (expected: 2927) in {"jsonrpc":"2.0","id":2927,"method":"eth_blockNumber","params":[]}
    at F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_web3-core-requestmanager@1.6.0@web3-core-requestmanager\lib\index.js:296:29
    at XMLHttpRequest.request.onreadystatechange (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_web3-providers-http@1.6.0@web3-providers-http\lib\index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
PS F:\11\Sniper-Bot-main\Sniper-Bot-main>

**Comment by forza-panino** [comment]
Can you please give more context about this? Complete console output from start (censoring the private_key) would be useful (e.g. Wallet configuration, target address, etc)

**Comment by leonxs** [comment]
You have launched the bot with the following settings:
Mode: presale
Delay: off
Net: mainnet
Do you want to change number of delay blocks? (y/n): n
Delay blocks number has not been changed.

Checking wallet configuration...
Found the following wallet configuration:
Private key: ***
Gas amount: 550000
Gas price: 12
Amount: 0.6
Do you want to change wallet configuration? (y/n): y
Starting configuration procedure now.

Insert private_key: ***
You digited ***
Confirm? (y/n): y

Insert gas_amount: 600000
You digited 600000
Confirm? (y/n): y

Insert gas_price: 15
You digited 15
Confirm? (y/n): y

Insert amount: 0.6
You digited 0.6
Confirm? (y/n): y

Here's the new wallet configuration:
Private key: ***
Gas amount: 600000
Gas price: 15
Amount: 0.6

Starting presale bot with the chosen settings...
Insert target address: 0x9f93A9E624092f10B98F59FD6d5b3cb5AdFBb599
You digited 0x9f93A9E624092f10B98F59FD6d5b3cb5AdFBb599
Confirm? (y/n): y

You will now be asked for time of presale start. Please, use your LOCAL TIME.
Insert start hour: 20
You digited 20
Confirm? (y/n): y
Insert start minute: 0
You digited 0
Confirm? (y/n): y
The bot will snipe at the given time today. Do you want to set it to snipe tomorrow instead? (y/n): n
Time of presale start has been set to 20:0 LOCAL TIME.
Waiting for time to come...
F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_web3-core-requestmanager@1.6.0@web3-core-requestmanager\lib\index.js:296     
            return callback(new Error(`Wrong response id ${result.id} (expected: ${payload.id}) in ${JSON.stringify(payload)}`));
                            ^

Error: Wrong response id 2005236270897797 (expected: 18596) in {"jsonrpc":"2.0","id":18596,"method":"eth_blockNumber","params":[]}
    at F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_web3-core-requestmanager@1.6.0@web3-core-requestmanager\lib\index.js:296:29
    at XMLHttpRequest.request.onreadystatechange (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_web3-providers-http@1.6.0@web3-providers-http\lib\index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (F:\11\Sniper-Bot-main\Sniper-Bot-main\node_modules\_xhr2-cookies@1.1.0@xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
PS F:\11\Sniper-Bot-main\Sniper-Bot-main>

**Comment by forza-panino** [comment]
Mh, looks like a library bug.
Did you get this error only once or every time you've tried the bot?

**Comment by leonxs** [comment]
yeah, every time I run this bot a few min later

**Comment by forza-panino** [comment]
Seems strange, gonna look further into it

**Comment by leonxs** [comment]
thank u, waiting for ur solution
